/*
 * =========================================================
 *  🇺🇦 🇺🇦 🇺🇦 🇺🇦 🇺🇦 🇺🇦 🇺🇦 GitLab API 🇺🇦 🇺🇦 🇺🇦 🇺🇦 🇺🇦 🇺🇦 🇺🇦
 * =========================================================
 * Copyright (c) 2019-2023
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */
const https = require('https')
const HttpResponse = require("./HttpResponse");

class Request {

    /**
     * @type {Request}
     */
    static #instance = null;
    methods = ['get', 'head', 'delete', 'patch', 'post', 'put', 'options'];

    constructor() {
        for (let m of this.methods) this[m] = this.#request;
    }

    /**
     * Singleton of Request
     * @return {Request|*}
     */
    static getInstance() {
        if (!this.#instance) return this.#instance = new Request();
        return this.#instance;
    }

    /**
     * Determines whether a given HTTP response is considered "good".
     * This function evaluates the provided response and returns a boolean
     * indicating its validity or success state, based on the criteria defined
     * in the `HttpResponse.isGood` method.
     *
     * @param {Object} res - The HTTP response object that needs to be evaluated.
     * @returns {boolean} - Returns true if the response is deemed "good", otherwise false.
     */
    static isGood = (res) => {
        return HttpResponse.isGood(res)
    }

    /**
     * Generates an HTTP response.
     *
     * @param {any} v - The value or payload to include in the response.
     * @param {any} res - The response object used to send the HTTP response.
     * @return {any} The HTTP response generated by the method.
     */
    static response(v, res) {
        return HttpResponse.response(v, res)
    }

    /**
     * Sends an HTTP request to the specified URL with the given options.
     * This method provides support for timeout handling, body data transmission,
     * and header management.
     *
     * @param {string} url The URL to which the request is sent.
     * @param {Object} options Configuration options for the request, such as method, headers, body, etc.
     * @param {string} [options.method] The HTTP method (e.g., GET, POST).
     * @param {Object} [options.headers] An object representing request headers.
     * @param {string|Buffer} [options.body] The body of the request (used for POST, PUT, etc.).
     * @param {number} [options.timeout] Optional timeout value in milliseconds.
     *
     * @return {Promise<Object|Error>} A Promise that resolves to the server's response object
     * if the request is successful, or an Error if the request fails or times out.
     */
    #request(url, options) {
        const {body} = options;
        if (body) delete options['body']
        options = {
            ...options,
            ...(body && {headers: {...options.headers, 'Content-Length': body.length}}),
            timeout: 30000,
        }
        return new Promise((resolve) => {
            const req = https.request(url, options, (res) => {
                if (!Request.isGood(res)) {
                    return resolve(Request.response({
                        message: res.statusMessage,
                        statusCode: res.statusCode,
                        method: options.method,
                        url
                    }, res));
                }
                const data = []
                res.on('data', (chunk) => data.push(chunk))
                res.on('end', () => {
                    resolve(Request.response(Buffer.concat(data).toString(), res))
                })
            })
            req.on('error', (err) => {
                resolve(Request.response(err, {statusCode: 500}))
            })
            req.on('timeout', () => {
                req.destroy()
                resolve(new Error('Request time out'))
            })
            if (body) req.write(body)
            req.end()
        })
    }
}

/**
 * @param {string} url
 * @param {object:{method,headers,body}} options
 * @return {Promise<{}>}
 */
module.exports = (url, options) => {
    const r = Request.getInstance()
    const m = [(options.method || 'get').toLowerCase()]
    return r[m](url, options)
};